### ISSUE TITLE
[FEATURE] Gestion des Signalements - Signaler une Anomalies sur les Fiches d’Application

### ISSUE THREAD

**Issue by Carolinedanslesnuages** [dnum-mi/referentiel-applications#178]
## Gestion des Signalements d’Anomalies sur les Fiches d’Application

**En tant qu’utilisateur** du référentiel des applications, 
**je souhaite** pouvoir signaler des anomalies sur les fiches d’application et permettre aux porteurs de les gérer efficacement, **afin de** garantir la qualité et la fiabilité des données.

**Pour répondre à cela :** 

#### Ajouter une fonctionnalité complète:
- de gestion des signalements d’anomalies, permettant aux utilisateurs de signaler des erreurs sur les fiches d’application via **un formulaire**, 
de suivre l’évolution de leurs demandes, et offrant aux porteurs d’application les outils nécessaires pour recevoir des notifications, consulter, gérer et résoudre ces signalements efficacement.

### Base fonctionnelle:

- [x]  **Signaler une anomalie**
	•	En tant qu’ utilisateur,
	•	je veux pouvoir initier un signalement d’anomalie en cliquant sur un bouton dédié, faire mon retour dans un champs texte,
	•	afin de signaler efficacement les erreurs identifiées et faciliter leur rectification.

- [x] **Créer un modèle de données pour les signalements**
	•	En tant que développeur back-end,
	•	je veux un modèle structuré pour représenter les signalements dans la base de données,
	•	afin de stocker et gérer efficacement les informations.

- [x] **Ajouter un endpoint API pour créer un signalement**
	•	En tant que développeur front-end,
	•	je veux un endpoint REST permettant d’envoyer les données du formulaire de signalement au serveur,
	•	afin de enregistrer les anomalies signalées.

- [x]  **Ajouter une migration Prisma pour le modèle des signalements**
	•	En tant que développeur back-end,
	•	je veux appliquer une migration pour ajouter la table des signalements dans la base de données,
	•	afin de permettre leur stockage et leur gestion.

### Suivi utilisateur

- [x] **Enregistrer les signalements dans le système**

	•	En tant que administrateur,
	•	je veux que chaque signalement d’anomalie soit enregistré avec les informations fournies,
	•	afin de garder une trace des erreurs signalées pour les traiter efficacement.

- [x] #183

- [ ] #231

**Comment by Carolinedanslesnuages** [comment]
Schema : 
model AnomalyNotification {
  id            String                    @id @default(uuid())
  applicationId String
  notifierId    String
  status        AnomalyNotificationStatus @default(in_pending)
  createdAt     DateTime                  @default(now())
  updatedAt     DateTime                  @updatedAt

  history     AnomalyNotificationHistory[]
  application Application?                 @relation("ApplicationAnomalyNotification", fields: [applicationId], references: [id])

  @@map("AnomalyNotification")
}

model AnomalyNotificationHistory {
  id                  String                    @id @default(uuid())
  issueNotificationId String
  action              String
  status              AnomalyNotificationStatus
  date                DateTime                  @default(now())

  issueNotification AnomalyNotification @relation(fields: [issueNotificationId], references: [id])

  @@map("AnomalyNotificationHystory")
}

enum AnomalyNotificationStatus {
  in_pending
  in_progress
  done
}

**Comment by Carolinedanslesnuages** [comment]
⚠️ Si je connais la correction il faut que le responsable de l'application fasse la modification. Donc En tant qu'utilisateur je veux pouvoir faire la modification moi-même.
